# Generated by Django 5.2.3 on 2025-06-14 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=False)),
                ("days_active", models.JSONField(help_text="Days like ['Mon', 'Tue']")),
                ("base_distance", models.FloatField(help_text="Base distance in KM")),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "additional_price_per_km",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PricingConfigLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pricing_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pricing.pricingconfig",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeMultiplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_minutes", models.PositiveIntegerField()),
                ("max_minutes", models.PositiveIntegerField()),
                ("multiplier", models.FloatField()),
                (
                    "pricing_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_multipliers",
                        to="pricing.pricingconfig",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaitingCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("free_minutes", models.PositiveIntegerField(default=3)),
                ("rate_per_3_min", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "pricing_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waiting_charges",
                        to="pricing.pricingconfig",
                    ),
                ),
            ],
        ),
    ]
